server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  main:
    banner-mode: log
management:
  endpoint:
     loggers:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: *
logging:
  level:
    org.springframework.jdbc.core: TRACE